---
abstract: 'Basic plugins to maintain and release CPAN dists, without a module builder'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-BasicWithoutMM
requires:
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-BasicWithoutMM
  repository: git://github.com/Leont/dist-zilla-pluginbundle-basicwithoutmm.git
version: 0.001
